go_hire/go_hire/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import include, path

# user/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from user import views

urlpatterns = [
    path('contests/', include('contests.urls')),
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^user/', include('user.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^judge/', include('judge.urls')),
    url(r'^hiring/', include('interview.urls')),
    url(r'^util/', include('util.urls')),
]

go_hire/user/urls.py
# user/urls.py
from django.conf.urls import url
from user import views
# SET THE NAMESPACE!
app_name = 'user'

# Be careful setting the name to just /login use user-login instead!
urlpatterns = [
    
    url(r'^register/$', views.register,name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^profile/$', views.profile_save, name='profile_save'),
]

go_hire/user/models.py
from django.db import models

# Create your models here.
# user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    ctc = models.CharField(blank=True, max_length=10)
    current_company = models.CharField(blank=True, max_length=50)
    resume = models.FileField(upload_to='resumes', blank=True)
    name = models.CharField(blank=True, max_length=50)


def __str__(self):
    return self.user.username

go_hire/user/forms.py
# dappx/forms.py
from django import forms
from user.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'ctc', 'current_company', 'resume', 'name')

go_hire/user/views.py
from django.shortcuts import render

# Create your views here.
# user/views.py
from django.shortcuts import render
from user.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json


def index(request):
    return render(request, 'user/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile_save(request):
    if request.method == 'POST':
        profile_form = UserProfileInfoForm(data=request.POST)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            if 'resume' in request.FILES:
                profile.resume = request.FILES['resume']
            profile.save()
            return JsonResponse({'status': True, 'error': None})
        else:
            print(profile_form.errors)
        return JsonResponse({'status': True, 'error': 'profile data is not valid'})


def register(request):
    registered = False
    error_message = ''
    if request.method == 'POST':
        user_form = UserForm(data=json.loads(request.body))
        if user_form.is_valid():
            try:
                user = user_form.save()
                user.set_password(user.password)
                registered = True
                user.save()
            except Exception as ex:
                error_message = 'User already register.'

        else:
            print(user_form.errors)
    data = {'registered': registered, 'error_message': error_message, 'is_staff': 1, 'user_id': user.id}
    return JsonResponse(data)

    #     profile_form = UserProfileInfoForm(data=request.POST)
    #     if user_form.is_valid() and profile_form.is_valid():
    #         user = user_form.save()
    #         user.set_password(user.password)
    #         user.save()
    #         profile = profile_form.save(commit=False)
    #         profile.user = user
    #         if 'profile_pic' in request.FILES:
    #             print('found it')
    #         profile.save()
    #         registered = True
    #     else:
    #         print(user_form.errors,profile_form.errors)
    # else:
    #     user_form = UserForm()
    #     profile_form = UserProfileInfoForm()
    # return render(request, 'user/registration.html',
    #               {'user_form': user_form,
    #                'profile_form': profile_form,
    #                'registered': registered})


def user_login(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        username = data.get('username')
        password = data.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return JsonResponse({'user_id': user.id, 'status': True, 'error': ''})
            else:
                return JsonResponse({'status': True, 'error': 'Your account was inactive'})
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return JsonResponse({'status': True, 'error': "Invalid login details given"})
    else:
        return JsonResponse({'status': True, 'error': "Invalid login details given"})

go_hire/templates/user/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Staff</a></li>
          <li><a class="navbar-link" href="{% url 'user:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'user:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

go_hire/templates/user/index.html
{% extends "user/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Go-Hire !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

go_hire/templates/user/login.html
{% extends 'user/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'user:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

go_hire/templates/user/registration.html
{% extends "user/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}